### ISSUE TITLE
Keeps saying Install Driver. ? 

### ISSUE THREAD

**Issue by FurqanHanif** [Magisk-Modules-Repo/ViPER4Android#2] opened 2017-10-14 18:46 UTC
Hello . 
i am having issue with this module , it keeps saying Install Driver, i installed many times and restarted my phone but still same. any fix for that.. ? 
i am using Latest Magisk Version (14.3)
Thanks.

**Comment by ShadySquirrel** [comment] 2017-10-14 20:54
That sounds like issues with SELinux injection. Will check tomorrow when I update my device (I'm still using 14.2).

**Comment by ShadySquirrel** [comment] 2017-10-15 09:22
I'm gonna need more info - ROM, device, android version, logs etc. All fine here.

**Comment by hexian000** [comment] 2017-10-16 04:44
Same issue:
OnePlus 3T, H2OS latest, based on Android 7.1.1
It's not my phone so I can't get logs soon.
Maybe I paste it here later.

**Comment by hexian000** [comment] 2017-10-16 04:45
ROM has a built-in Dirac Sound

**Comment by ShadySquirrel** [comment] 2017-10-16 08:59
Until someone provides logs, only way you can check if it's selinux issue or something with ROM is to disable SELinux and try.

**Comment by FurqanHanif** [comment] 2017-10-17 17:05
i Reverted back to 14.2 but still having same issue. i have to restart like 10-20 times to make it works and sometimes my Phone randomly reboots too (which is Because of SELINUX i guess)... 
Magisk Log File attached. 
[magisk_error_20171017_215552.log](https://github.com/Magisk-Modules-Repo/ViPER4Android/files/1391927/magisk_error_20171017_215552.log)

**Comment by ShadySquirrel** [comment] 2017-10-17 17:41
I'm gonna need logcat and kmsg, but I can tell you one thing: my module is clashing with Audio Mod Lib. Remove it and try without it.

**Comment by FurqanHanif** [comment] 2017-10-18 11:48
Uninstalled Audio Mod LIb Module.. Still Same issue.
Latest Log Files Attached.
[logcat.txt](https://github.com/Magisk-Modules-Repo/ViPER4Android/files/1394440/logcat.txt)
[magisk_error_20171018_163214.log](https://github.com/Magisk-Modules-Repo/ViPER4Android/files/1394441/magisk_error_20171018_163214.log)
[dmesg.txt](https://github.com/Magisk-Modules-Repo/ViPER4Android/files/1394442/dmesg.txt)

**Comment by ShadySquirrel** [comment] 2017-10-18 12:05
You're on MIUI, damn.

I can't see if SELinux rules are injected, dmesg output isn't complete - sepolicy injection happens on really early boot stage, and that part of the kernel log is missing.

Module is there, configuration files are there, I can see module is loaded properly. You may want to try running post-fs-data.sh from /magisk/viper4android and check if SELinux rules are actually injected or not - call that script and capture dmesg after, then open the V4A app and check if error is gone.

**Comment by FurqanHanif** [comment] 2017-10-18 15:12
Yes, Unfortunately i am on Crappy MIUI.. :( 
Latest Logs attached after running post-fs-data.sh
Nops, Error  is still there. 
[magisk_error_20171018_195224.log](https://github.com/Magisk-Modules-Repo/ViPER4Android/files/1395109/magisk_error_20171018_195224.log)
[dmesg (2).txt](https://github.com/Magisk-Modules-Repo/ViPER4Android/files/1395110/dmesg.2.txt)
[logcat (1).txt](https://github.com/Magisk-Modules-Repo/ViPER4Android/files/1395111/logcat.1.txt)

**Comment by ShadySquirrel** [comment] 2017-10-18 16:08
This is funny, driver is there, configs are there, sepolicy is loaded. It looks possibly as a module clash or general incompatibility with MIUI. 
Can you disable modules one by one and check if V4A started working?

**Comment by FurqanHanif** [comment] 2017-10-18 18:09
DIsabled All modules (Only v4A Enabled) . Still Same issue.. Sometime works and sometime Not..:/   i just don't understand if it is incompatible then why 1 out of 40 tries it works.. :/  it should be like 0 out 40 if it's incomaptiable i guess..

**Comment by FurqanHanif** [comment] 2017-10-18 19:12
OK, SO after Reinstalling Module, It works.. i attached the Log files so you can figure out the problem by comparing with previous logs.. 
Thanks for all Your Help. :) 
[magisk_error_20171019_000450.log](https://github.com/Magisk-Modules-Repo/ViPER4Android/files/1395997/magisk_error_20171019_000450.log)
[dmesg (3).txt](https://github.com/Magisk-Modules-Repo/ViPER4Android/files/1395998/dmesg.3.txt)
[logcat.txt](https://github.com/Magisk-Modules-Repo/ViPER4Android/files/1395999/logcat.txt)

**Comment by ShadySquirrel** [comment] 2017-10-18 22:25
I've checked logs, it's nothing different compared to earlier ones. My blind guess is that having both my V4A and AML somehow messed-up audio_effects.conf and it got copied back to V4A's directory (take into consideration - I'm changing configuration during installation, not runtime) so even if module was really present, sepolicy loaded etc., V4A app couldn't find it because it wasn't in configuration file.

I'm closing this and marking as fixed.

**Closed by ShadySquirrel** 2017-10-18 22:25 UTC

**Comment by hexian000** [comment] 2017-10-21 11:22
I replaced the Viper4Android app with the official one, the problem is gone.
